blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/mysci4k/test/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://github.com/mysci4k/test#readme
    about: Read the project documentation
